repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
        exclude: _pytest/debugging.py
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        language_version: python3
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.3.0
    hooks:
    -   id: pyupgrade
        args: [--keep-percent-format]
